Update `hypothesis`
This required addressing some errors from `mypy`:

    tests/integration/test_setting_combinations.py:20: error: "SearchStrategy" expects no type arguments, but 1 given  [type-arg]
    tests/integration/test_hypothesmith.py:36: error: "SearchStrategy" expects no type arguments, but 1 given  [type-arg]