Update typing for `setuptools`
The inspiration for this change was the following warning from `poetry`:

    Warning: The locked version 0.1.3 for types-pkg-resources is a yanked
    version. Reason for being yanked: Use types-setuptools instead

Following that, adding `types-setuptools` allowed the removal of some
`type: ignore` comments, which then lead to a single issue needing to be
fixed:

    tests/unit/test_setuptools_command.py:8: error: Argument 1 to "ISortCommand" has incompatible type "distutils.dist.Distribution"; expected "setuptools.dist.Distribution"  [arg-type]